// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package lockfile

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	config "github.com/nikeee/cappu/internal/config"
	packages "github.com/nikeee/cappu/internal/packages"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalLockfile(in *jlexer.Lexer, out *coordinates) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "groupId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GroupID = string(in.String())
			}
		case "artifactId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ArtifactID = string(in.String())
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalLockfile(out *jwriter.Writer, in coordinates) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"groupId\":"
		out.RawString(prefix[1:])
		out.String(string(in.GroupID))
	}
	{
		const prefix string = ",\"artifactId\":"
		out.RawString(prefix)
		out.String(string(in.ArtifactID))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v coordinates) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalLockfile(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v coordinates) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalLockfile(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *coordinates) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalLockfile(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *coordinates) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalLockfile(l, v)
}
func easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalLockfile1(in *jlexer.Lexer, out *Lockfile) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = int(in.Int())
			}
		case "roots":
			easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalConfig(in, &out.Roots)
		case "packages":
			if in.IsNull() {
				in.Skip()
				out.Packages = nil
			} else {
				in.Delim('[')
				if out.Packages == nil {
					if !in.IsDelim(']') {
						out.Packages = make([]LockedPackage, 0, 0)
					} else {
						out.Packages = []LockedPackage{}
					}
				} else {
					out.Packages = (out.Packages)[:0]
				}
				for !in.IsDelim(']') {
					var v1 LockedPackage
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Packages = append(out.Packages, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "processorPackages":
			if in.IsNull() {
				in.Skip()
				out.ProcessorPackages = nil
			} else {
				in.Delim('[')
				if out.ProcessorPackages == nil {
					if !in.IsDelim(']') {
						out.ProcessorPackages = make([]LockedPackage, 0, 0)
					} else {
						out.ProcessorPackages = []LockedPackage{}
					}
				} else {
					out.ProcessorPackages = (out.ProcessorPackages)[:0]
				}
				for !in.IsDelim(']') {
					var v2 LockedPackage
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.ProcessorPackages = append(out.ProcessorPackages, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "testPackages":
			if in.IsNull() {
				in.Skip()
				out.TestPackages = nil
			} else {
				in.Delim('[')
				if out.TestPackages == nil {
					if !in.IsDelim(']') {
						out.TestPackages = make([]LockedPackage, 0, 0)
					} else {
						out.TestPackages = []LockedPackage{}
					}
				} else {
					out.TestPackages = (out.TestPackages)[:0]
				}
				for !in.IsDelim(']') {
					var v3 LockedPackage
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.TestPackages = append(out.TestPackages, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalLockfile1(out *jwriter.Writer, in Lockfile) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Version))
	}
	{
		const prefix string = ",\"roots\":"
		out.RawString(prefix)
		easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalConfig(out, in.Roots)
	}
	{
		const prefix string = ",\"packages\":"
		out.RawString(prefix)
		if in.Packages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Packages {
				if v4 > 0 {
					out.RawByte(',')
				}
				(v5).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.ProcessorPackages) != 0 {
		const prefix string = ",\"processorPackages\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v6, v7 := range in.ProcessorPackages {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.TestPackages) != 0 {
		const prefix string = ",\"testPackages\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.TestPackages {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Lockfile) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalLockfile1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Lockfile) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalLockfile1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Lockfile) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalLockfile1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Lockfile) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalLockfile1(l, v)
}
func easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalConfig(in *jlexer.Lexer, out *config.Dependencies) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "api":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.API = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v10 string
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = string(in.String())
					}
					(out.API)[key] = v10
					in.WantComma()
				}
				in.Delim('}')
			}
		case "implementation":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Implementation = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v11 string
					if in.IsNull() {
						in.Skip()
					} else {
						v11 = string(in.String())
					}
					(out.Implementation)[key] = v11
					in.WantComma()
				}
				in.Delim('}')
			}
		case "annotationProcessor":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.AnnotationProcessor = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v12 string
					if in.IsNull() {
						in.Skip()
					} else {
						v12 = string(in.String())
					}
					(out.AnnotationProcessor)[key] = v12
					in.WantComma()
				}
				in.Delim('}')
			}
		case "testImplementation":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.TestImplementation = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v13 string
					if in.IsNull() {
						in.Skip()
					} else {
						v13 = string(in.String())
					}
					(out.TestImplementation)[key] = v13
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalConfig(out *jwriter.Writer, in config.Dependencies) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"api\":"
		out.RawString(prefix[1:])
		if in.API == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v14First := true
			for v14Name, v14Value := range in.API {
				if v14First {
					v14First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v14Name))
				out.RawByte(':')
				out.String(string(v14Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"implementation\":"
		out.RawString(prefix)
		if in.Implementation == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v15First := true
			for v15Name, v15Value := range in.Implementation {
				if v15First {
					v15First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v15Name))
				out.RawByte(':')
				out.String(string(v15Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"annotationProcessor\":"
		out.RawString(prefix)
		if in.AnnotationProcessor == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v16First := true
			for v16Name, v16Value := range in.AnnotationProcessor {
				if v16First {
					v16First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v16Name))
				out.RawByte(':')
				out.String(string(v16Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"testImplementation\":"
		out.RawString(prefix)
		if in.TestImplementation == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v17First := true
			for v17Name, v17Value := range in.TestImplementation {
				if v17First {
					v17First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v17Name))
				out.RawByte(':')
				out.String(string(v17Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}
func easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalLockfile2(in *jlexer.Lexer, out *LockedPackage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "coordinates":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coordinates).UnmarshalEasyJSON(in)
			}
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Source = string(in.String())
			}
		case "sha256":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sha256 = Sha256(in.String())
			}
		case "licenses":
			if in.IsNull() {
				in.Skip()
				out.Licenses = nil
			} else {
				in.Delim('[')
				if out.Licenses == nil {
					if !in.IsDelim(']') {
						out.Licenses = make([]packages.License, 0, 2)
					} else {
						out.Licenses = []packages.License{}
					}
				} else {
					out.Licenses = (out.Licenses)[:0]
				}
				for !in.IsDelim(']') {
					var v18 packages.License
					easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalPackages(in, &v18)
					out.Licenses = append(out.Licenses, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalLockfile2(out *jwriter.Writer, in LockedPackage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coordinates\":"
		out.RawString(prefix[1:])
		(in.Coordinates).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	{
		const prefix string = ",\"sha256\":"
		out.RawString(prefix)
		out.String(string(in.Sha256))
	}
	if len(in.Licenses) != 0 {
		const prefix string = ",\"licenses\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v19, v20 := range in.Licenses {
				if v19 > 0 {
					out.RawByte(',')
				}
				easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalPackages(out, v20)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LockedPackage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalLockfile2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LockedPackage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalLockfile2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LockedPackage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalLockfile2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LockedPackage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalLockfile2(l, v)
}
func easyjsonAee5a8cfDecodeGithubComNikeeeCappuInternalPackages(in *jlexer.Lexer, out *packages.License) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAee5a8cfEncodeGithubComNikeeeCappuInternalPackages(out *jwriter.Writer, in packages.License) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.URL != "" {
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	out.RawByte('}')
}
