package compiler

// textToKeyword maps each reserved word (and the reserved literals
// true/false/null) to its kind. Contextual keywords (var, yield, record,
// sealed, ...) are intentionally absent: they are scanned as identifiers and
// recognized positionally by the parser. Port of utilities.ts textToKeyword.
var textToKeyword = map[string]SyntaxKind{
	"abstract":     AbstractKeyword,
	"assert":       AssertKeyword,
	"boolean":      BooleanKeyword,
	"break":        BreakKeyword,
	"byte":         ByteKeyword,
	"case":         CaseKeyword,
	"catch":        CatchKeyword,
	"char":         CharKeyword,
	"class":        ClassKeyword,
	"const":        ConstKeyword,
	"continue":     ContinueKeyword,
	"default":      DefaultKeyword,
	"do":           DoKeyword,
	"double":       DoubleKeyword,
	"else":         ElseKeyword,
	"enum":         EnumKeyword,
	"extends":      ExtendsKeyword,
	"final":        FinalKeyword,
	"finally":      FinallyKeyword,
	"float":        FloatKeyword,
	"for":          ForKeyword,
	"goto":         GotoKeyword,
	"if":           IfKeyword,
	"implements":   ImplementsKeyword,
	"import":       ImportKeyword,
	"instanceof":   InstanceofKeyword,
	"int":          IntKeyword,
	"interface":    InterfaceKeyword,
	"long":         LongKeyword,
	"native":       NativeKeyword,
	"new":          NewKeyword,
	"package":      PackageKeyword,
	"private":      PrivateKeyword,
	"protected":    ProtectedKeyword,
	"public":       PublicKeyword,
	"return":       ReturnKeyword,
	"short":        ShortKeyword,
	"static":       StaticKeyword,
	"strictfp":     StrictfpKeyword,
	"super":        SuperKeyword,
	"switch":       SwitchKeyword,
	"synchronized": SynchronizedKeyword,
	"this":         ThisKeyword,
	"throw":        ThrowKeyword,
	"throws":       ThrowsKeyword,
	"transient":    TransientKeyword,
	"try":          TryKeyword,
	"void":         VoidKeyword,
	"volatile":     VolatileKeyword,
	"while":        WhileKeyword,
	"true":         TrueKeyword,
	"false":        FalseKeyword,
	"null":         NullKeyword,
}
